name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: 'healtcare_db_user'
      DB_PASSWORD: '1lNR2y84HYyEftDx0Ha5ZuMtyV8Puyrv'
      DB_DATABASE: 'healthub_db'
      DB_HOST_PORT: '5432'
      API_HOST_PORT: '4000'
      API_CONTAINER_PORT: '4000'
      APP_HOST_PORT: '3000'
      ENV: 'staging'
      API_JWT_SECRET: '123password'
      API_URL: 'http://localhost:4000'
      DB_HOST: 'db'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Services
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Backend Tests with Coverage
        run: |
          docker-compose run --rm backend npm run coverage

      - name: Upload Coverage to Codecov
        run: |
          npm install -g codecov
          npx codecov --file=coverage/lcov.info --disable=gcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy Services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Validate Deployment
        run: |
          echo 'Waiting for backend to initialize...'
          sleep 10
          curl -f http://localhost:4000/ping || exit 1

  notify:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        run: |
          echo "Job finished with status: ${{ job.status }}"
